site_name: Documentação Guia de Acessiblidade Digital

nav:
  - Página Inicial: index.md
  - Guia de Acessiblidade:
      - Sobre: guia_acessibilidade/sobre.md
      - Gestão de Projetos: guia_acessibilidade/guia_gestao.md
      - Desenvolvimento: guia_acessibilidade/guia_desenvolvimento.md
      - Design: guia_acessibilidade/guia_design.md
      - Conteúdo: guia_acessibilidade/guia_conteudo.md
  - Referências e Ferramentas: referencias/referencias.md
  
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/globe-light
        name: Dark mode
      primary: black
      accent: black
    - scheme: slate
      toggle:
        icon: material/globe-light-outline
        name: Light mode
      primary: white
      accent: black

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist:
      clickable_checkbox: true

extra_css:
  - css/custom.css