site_name: Documentação Guia de Acessiblidade Digital

nav:
  - Página Inicial: index.md
  - Guia de Acessiblidade: guia_acessibilidade/guia_acessibilidade.md
  - Referências: referencias/referencias.md
  
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: pt

  palette:
    - scheme: default
      toggle:
        icon: material/globe-light
        name: Dark mode
      primary: black
      accent: black
    - scheme: slate
      toggle:
        icon: material/globe-light-outline
        name: Light mode
      primary: white
      accent: black

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.emoji
  - pymdownx.tasklist:
      clickable_checkbox: true

extra_css:
  - css/custom.css